gameservice:
  serverid: 1                          # 游戏服ID
  port: 8000                           # 游戏服务端口
  passportkey: 1c870b995ad             # passport Key
  gameplaymanageraddr: localhost:8777  # gameplay manager 地址

fastway:
  serveraddr: 127.0.0.1:10000          # 网关服务端地址
  authkey: 1c870b995ad                 # 网关密钥

db:                                    # 数据库相关配置
  host: 127.0.0.1                      # 数据库地址
  port: 3306                           # 数据库端口
  user: root                           # 数据库用户名
  password:                            # 数据库密码
  name: game_service                   # 数据库名称

log:                                   # 日志相关配置
  dir: log                             # 日志存放目录
  name: game_service.log               # 日志文件名称
  maxsize: 0                           # 单个日志文件最大字节数，单位为兆
  maxage: 0                            # 日志文件最大保留天数
  maxbackups: 0                        # 日志文件最大保留个数
  compress: false                      # 日志文件是否压缩
  logchansize: 20000                   # 日志缓冲区大小
  releasemode: false                   # 是否开启 release 模式