// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: watcher.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MatchPodResponse_MatchPodResponseStatus int32

const (
	MatchPodResponse_Ok           MatchPodResponse_MatchPodResponseStatus = 0
	MatchPodResponse_ParamError   MatchPodResponse_MatchPodResponseStatus = 1
	MatchPodResponse_UnknownError MatchPodResponse_MatchPodResponseStatus = 2
)

// Enum value maps for MatchPodResponse_MatchPodResponseStatus.
var (
	MatchPodResponse_MatchPodResponseStatus_name = map[int32]string{
		0: "Ok",
		1: "ParamError",
		2: "UnknownError",
	}
	MatchPodResponse_MatchPodResponseStatus_value = map[string]int32{
		"Ok":           0,
		"ParamError":   1,
		"UnknownError": 2,
	}
)

func (x MatchPodResponse_MatchPodResponseStatus) Enum() *MatchPodResponse_MatchPodResponseStatus {
	p := new(MatchPodResponse_MatchPodResponseStatus)
	*p = x
	return p
}

func (x MatchPodResponse_MatchPodResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchPodResponse_MatchPodResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_watcher_proto_enumTypes[0].Descriptor()
}

func (MatchPodResponse_MatchPodResponseStatus) Type() protoreflect.EnumType {
	return &file_watcher_proto_enumTypes[0]
}

func (x MatchPodResponse_MatchPodResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchPodResponse_MatchPodResponseStatus.Descriptor instead.
func (MatchPodResponse_MatchPodResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{1, 0}
}

type MatchPodCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`                              // 命名空间
	LabelSelector string `protobuf:"bytes,2,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"` // 标签匹配
}

func (x *MatchPodCondition) Reset() {
	*x = MatchPodCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchPodCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPodCondition) ProtoMessage() {}

func (x *MatchPodCondition) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPodCondition.ProtoReflect.Descriptor instead.
func (*MatchPodCondition) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{0}
}

func (x *MatchPodCondition) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MatchPodCondition) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

type MatchPodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status MatchPodResponse_MatchPodResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=MatchPodResponse_MatchPodResponseStatus" json:"status,omitempty"` // 返回状态
	Pods   []*Pod                                  `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`                                                   // pod 列表
}

func (x *MatchPodResponse) Reset() {
	*x = MatchPodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchPodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPodResponse) ProtoMessage() {}

func (x *MatchPodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPodResponse.ProtoReflect.Descriptor instead.
func (*MatchPodResponse) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{1}
}

func (x *MatchPodResponse) GetStatus() MatchPodResponse_MatchPodResponseStatus {
	if x != nil {
		return x.Status
	}
	return MatchPodResponse_Ok
}

func (x *MatchPodResponse) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"` // pod 地址
}

func (x *Pod) Reset() {
	*x = Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_watcher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_watcher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_watcher_proto_rawDescGZIP(), []int{2}
}

func (x *Pod) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_watcher_proto protoreflect.FileDescriptor

var file_watcher_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x58, 0x0a, 0x11, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xb2, 0x01, 0x0a, 0x10, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28,
	0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x50, 0x6f, 0x64, 0x52, 0x04, 0x70, 0x6f, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x16, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22, 0x19,
	0x0a, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x32, 0x42, 0x0a, 0x0c, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x12, 0x12, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x11, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_watcher_proto_rawDescOnce sync.Once
	file_watcher_proto_rawDescData = file_watcher_proto_rawDesc
)

func file_watcher_proto_rawDescGZIP() []byte {
	file_watcher_proto_rawDescOnce.Do(func() {
		file_watcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_watcher_proto_rawDescData)
	})
	return file_watcher_proto_rawDescData
}

var file_watcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watcher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_watcher_proto_goTypes = []interface{}{
	(MatchPodResponse_MatchPodResponseStatus)(0), // 0: MatchPodResponse.MatchPodResponseStatus
	(*MatchPodCondition)(nil),                    // 1: MatchPodCondition
	(*MatchPodResponse)(nil),                     // 2: MatchPodResponse
	(*Pod)(nil),                                  // 3: Pod
}
var file_watcher_proto_depIdxs = []int32{
	0, // 0: MatchPodResponse.status:type_name -> MatchPodResponse.MatchPodResponseStatus
	3, // 1: MatchPodResponse.pods:type_name -> Pod
	1, // 2: WatchService.Watch:input_type -> MatchPodCondition
	2, // 3: WatchService.Watch:output_type -> MatchPodResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_watcher_proto_init() }
func file_watcher_proto_init() {
	if File_watcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_watcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchPodCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchPodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_watcher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_watcher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_watcher_proto_goTypes,
		DependencyIndexes: file_watcher_proto_depIdxs,
		EnumInfos:         file_watcher_proto_enumTypes,
		MessageInfos:      file_watcher_proto_msgTypes,
	}.Build()
	File_watcher_proto = out.File
	file_watcher_proto_rawDesc = nil
	file_watcher_proto_goTypes = nil
	file_watcher_proto_depIdxs = nil
}
