apiVersion: batch/v1
kind: Job
metadata:
  name: getip-job
spec:
  template:
    metadata:
      labels:
        app: getip-job
    spec:
      containers:
      - name: getip-test
        image: getip:latest
        imagePullPolicy: Never
      restartPolicy: Never
